chroma_data:
  path: '../chroma_data/'

sentence_transformer:
  embedding_model: 'paraphrase-multilingual-MiniLM-L12-v2'
  device: 'mps'

translator:
  threshold: 5000

relevance_threshold: 1

text_splitter:
  chunk_size: 1000
  chunk_overlap: 200